version: "3"
services:
  client-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - "./node_modules:/app/node_modules"
    command: ["npm", "run", "dev"]
